---
title: "bootcamp_day2"
author: "Ivan"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
here::here("data","gapminder5.csv")

# here::here replace the unique home that you can distribute across
gapminder <- read.csv(here::here("data",
                                 "gapminder5.csv"))
```

```{r}
str(gapminder)
```

## Converting Factors to Char

```{r}
gapminder$country<-as.character(gapminder$country)
gapminder$continent<-as.character(gapminder$continent)

```

## Create logged variables with a for loop
```{r}
for (i in 1:nrow(gapminder)){
  gapminder[i,'log_gdpPercap']<-log(gapminder[i,'gdpPercap'])
  gapminder[i,'log_pop']<-log(gapminder[i,'pop'])
  
}

```

## Vectorization way of taking log
```{r}
gapminder$vec_log_gdpPercap <- log(gapminder$gdpPercap)
all(gapminder$vec_log_gdpPercap == gapminder$log_gdpPercap)

```

## Find mean life expectancy for each year
```{r}

years <- unique(gapminder$year)

for (i in years) {
  mean_le <- mean(gapminder$lifeExp[gapminder$year == i], 
                  na.rm = T)
  print(paste0(i, ": ", mean_le))
}

```

```{r}
conts <- unique(gapminder$continent)

for (i in conts) {
  mean_le <- mean(gapminder$lifeExp[gapminder$continent == i], 
                  na.rm = T)
  print(paste0(i, ": ", mean_le))
}

```

```{r}
for (i in conts) {
  print(paste0("Continent: ", i))
  for (j in years) {
    mean_le <- mean(gapminder$lifeExp[gapminder$continent == i & 
                                          gapminder$year == j], 
                      na.rm = T)
    print(paste0(j, ": ", mean_le))
  }
  }


```

```{r}
for (i in conts) {
  print(paste0("Continent: ", i))
  for (j in years) {
    mean_le <- sd(gapminder$lifeExp[gapminder$continent == i & 
                                          gapminder$year == j], 
                      na.rm = T)
    print(paste0(j, ": ", mean_le))
  }
  }


```

## apply family only hides loops
```{r}
vars <- gapminder[, c("lifeExp", "pop", "gdpPercap")]
apply(vars, 2, mean,na.rm = T) # apply takes in a matrix, so 
# take whatever and coerce into matrix. So cannot take Char value.

# lapply
lapply(gapminder, mean,na.rm = T) # return a list

# sapply
sapply(years, function(x) mean(gapminder$lifeExp[gapminder$year == x])) # unlist lapply


```

## While loop
```{r}
i <-  1952 # define the interator

while (i < 1987) {
  sd_lf <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ": ", sd_lf)
        )
  i <- i + 5 # increase the iterator by the interval between years
}

```

```{r}
i <-  1987 # define the interator

while (i <= 2002) {
  sd_lf <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ": ", sd_lf)
        )
  i <- i + 5 # increase the iterator by the interval between years
}

```


```{r}
for (i in years) {
  if (i >= 1987) {
    mean_pop <- mean(gapminder$lifeExp[gapminder$year == i])
    print(paste0(i, ": ", mean_pop))
  } else {
    print("Sorry, year is less than 1987")
  }
}


```

## Function
```{r}
get_values <-
  function(df, variable = "continent") {
    vals <- unique(df[[variable]])
    print(paste0(variable, ": ", vals))
  }


```

```{r}

report_mean_sd <- 
  function(df, variable, country) {
    var <- df[[variable]][df$country == country]
    m_le <- mean(var)
    median_le <- median(var)
    min_le <- min(var)
    print(min_le)
    max_le <- max(var)
    
    cat("Country:", country, 
        "\nMean Life Expectancy:", m_le,
        "\nmedian Life Expectancy:", median_le,
        "\nmin Life Expectancy:", min_le,
        "\nmax Life Expectancy:", max_le
        )
  }

report_mean_sd(gapminder, "lifeExp", "Afghanistan")


```







